### ISSUE TITLE
[Bug]: Android tv apk

### ISSUE THREAD

**Issue by Yash55-spec** [siddharthsky/CustTermux#65]
### Problem description

![IMG_20241007_132413884_HDR](https://github.com/user-attachments/assets/23ca6c22-d5e3-45af-8a5f-4cb7a0030089)
![IMG_20241007_132437574_HDR](https://github.com/user-attachments/assets/1bcbabbb-25c2-4b55-8654-024218f77e2d)

### What steps will reproduce the bug?

After finish setup it's showing already login when I click in web tv version error code showing I uploaded the images please resolve this issue 

### System information

```shell
OnePlus y series Android tv
```

**Comment by riteshpal2005** [comment]
Facing the same issue in my OnePlus Y Series TV.

**Comment by siddharthsky** [comment]
Try using different port number other that 5001.

**Comment by riteshpal2005** [comment]
> Try using different port number other that 5001.

I changed Port 5002, and in my Y Series, the issue is resolved.

Thanks Dev.
