### ISSUE TITLE
[Bug]: MNX & MN+ channels bug.

### ISSUE THREAD

**Issue by akhil9810** [siddharthsky/CustTermux#72]
### Problem description

Two channels MNX & MN+ aren't playing.

### What steps will reproduce the bug?

Playing these two channels showing stream error.

### System information

```shell
Stream error.
```

**Comment by siddharthsky** [comment]
Just a heads-up: CustTermux doesn’t provide channels; it’s just a wrapper to run binaries. If you need help, create an issue [here](https://github.com/JioTV-Go/jiotv_go).
