### ISSUE TITLE
[Feature]: Favorite Channel List

### ISSUE THREAD

**Issue by Sid007007** [siddharthsky/CustTermux#73]
### Feature description

Sir If You Add Favorite Channel List Will be Very Helpful because Many Tv Channels And Each Time We Have To Go To List And Search Our Favorite Channel Like Cartoon Network And Pogo ETC. Other Chanel Are Not Useful For Kids

### Additional information

Yes

**Comment by Generation88** [comment]
> ### Feature description
> Sir If You Add Favorite Channel List Will be Very Helpful because Many Tv Channels And Each Time We Have To Go To List And Search Our Favorite Channel Like Cartoon Network And Pogo ETC. Other Chanel Are Not Useful For Kids
> 
> ### Additional information
> Yes
This can only be done on jio tv go

so close your issue

**Comment by ShubhamAtGH** [comment]
How to do that?

**Comment by siddharthsky** [comment]
Use the IPTV player for the desired feature; for now, this cannot be implemented in WebTV.
