### ISSUE TITLE
[Bug]: Current server status: stopped

### ISSUE THREAD

**Issue by adithyan-hermit** [siddharthsky/CustTermux#80]
### Problem description

Showing current server status stopped 

### What steps will reproduce the bug?

Showing current server status stopped 

### What is the expected behavior?

Showing current server status stopped 

### System information

```shell
Showing current server status stopped
```

**Comment by Nikhchan** [comment]
My local server status shows "stopped" and it gets logged out after the TV is on sleep mode.

I have to use the rerun option to get it going.

Is there anyway to periodically rerun it?

Or anyway to add option to rerun after wake up?
